## Case Study (google analytics)
## Sören Nonnengart
## 05-25-2022

###### ###### ###### ###### ###### ###### 
######### Ask Phase ####### ###### ###### 
###### ###### ###### ###### ###### ###### 

# About the company
Bellabeat is a high-tech company that manufactures health-focused smart products. One of the
founders, Urška Sršen, used her background as an artist to develop beautifully designed technology 
that informs and inspires women around the world. Collecting data on
  
  - activity, 
  - sleep, 
  - stress and
  - reproductive health 

has allowed Bellabeat to empower women with knowledge about their own health and habits. 
Since it was founded in 2013, Bellabeat has grown rapidly and quickly positioned itself as a 
tech-driven wellness company for women

# Questions for the analysis
  1. What are some trends in smart device usage?
    
     A: According to Statista, the current number of smartphone users worldwide today is 6.648 billion. 
     This means that 83.72 % of the world’s population owns a smartphone.The trend thus shows that in 
     the near future almost all people worldwide could own a smartphone. It is estimated that 7.33 billion 
     people could already own a smartphone by 2025.
     (Source: https://www.bankmycell.com/blog/how-many-phones-are-in-the-world#:~:text=According%20to%20Statista%2C%20the%20current,world's%20population%20owns%20a%20smartphone.)    
     Another interesting study by Seifert & Vandelanotte (2021) shows that 75.0% of older adults used at 
     least one mobile device; 22.9 % of them used health-related apps. Younger individuals and those with 
     a strong interest in new technology had a higher likelihood of using health apps
     (Source: https://www.researchgate.net/publication/354050165_The_Use_of_Wearables_and_Health_Apps_and_the_Willingness_to_Share_Self-Collected_Data_among_Older_Adults#:~:text=Results%2075.0%25%20of%20the%20participants,likelihood%20of%20using%20health%20apps.)
     According to Statista, it can also be shown that these apps are esspecially used for fitness-tracking 
     (Source: https://www.statista.com/forecasts/832132/usage-of-health-apps-and-smart-health-devices-in-the-us)
       
  2. How could these trends apply to Bellabeat customers?
    
    A: Bellabeat customers are perfectly fit into this trend because the probability is really high that more
    and more people will use a smartphone in the future. It is also a fact that health has become a really 
    important part in the people's daily life. Therefore, the probability is high that this trend will 
    continue
    
  3. How could these trends help influence Bellabeat marketing strategy 
  
    A: This trend shows that it could be more worthwhile to target a younger customer base with 
    Bellabeat's products. But there should also be an interest in targeting older people since it can 
    be assumed that demand here will also increase in the future.
    (Source: https://www.researchgate.net/publication/354050165_The_Use_of_Wearables_and_Health_Apps_and_the_Willingness_to_Share_Self-Collected_Data_among_Older_Adults#:~:text=Results%2075.0%25%20of%20the%20participants,likelihood%20of%20using%20health%20apps.)
  
# Business task
Identify potential opportunities for growth and recommendations for the Bellabeat marketing strategy 
improvement based on trends in smart device usage.


###################################################################################################
###################################################################################################

###### ###### ###### ###### ###### ###### 
####### ###### Prepare Phase ##### ######
###### ###### ###### ###### ###### ###### 

Which dataset will be used for the analysis?
- The data source used for this case study is called "FitBit Fitness Tracker Data". 
- This dataset is stored in Kaggle and was made available through Mobius.
- As it is suggested by google analytics and is free to download in Kaggle it is guaranteed
  that the data is open-source and can be used without hesitation for statistical analyses.
- These datasets were generated by respondents to a distributed survey via Amazon Mechanical Turk 
  between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker 
  data, including minute-level output for physical activity, heart rate, and sleep monitoring. 
  Variation between output represents use of different types of Fitbit trackers and individual 
  tracking behaviors/preferences.



## packages 
library(foreign)
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
library(janitor)
library(ggpubr)

## data.frame
# Directories
path1 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/results"   
path2 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/data_orig" #directory of original data
path3 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/data_prep" #directory of prepared datasets
path4 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/tables" 
path5 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/graphs" 

getwd()
setwd(path2)
getwd()

# read csv_data for analysis
activity <- read.csv("dailyActivity_merged.csv", na="NA", sep=",")
sleep <- read.csv("sleepDay_merged.csv", na="NA", sep=",")


# Now I will preview all the selected data frames for checking the summary of each column.
# Show first 10 observations for first 5 variables 
View(activity[1:10,1:5])
str(activity)

View(sleep[1:10,1:5])
str(sleep)

###### ###### ###### ###### ###### ######
###### ###### process phase ###### ######
###### ###### ###### ###### ###### ######

## showing NA-values
is.na(activity)
which(is.na(activity))

is.na(sleep)
which(is.na(sleep))
### count the number of NA values ---> (There are 0 NA-Values in the datasets)
sum(is.na(activity))
sum(is.na(sleep))

## Remove duplicates 
# First summarize duplicates
sum(duplicated(activity))
sum(duplicated(sleep)) # There are 3 duplicates in the sleep_day dataset
## remove the duplicates with the unique-function
sleep <- unique(sleep)

# rename columns for avoiding problems with case-sensitivity in R to lower case
activity <- rename_with(activity, tolower)
sleep <- rename_with(sleep, tolower)

# Now I'll use the clean names function in the Janitor package. This will automatically make sure that the 
# column names are unique and consistent. 
clean_names(activity)
clean_names(sleep)

## Time formatting
activity$activitydate=as.POSIXct(activity$activitydate, format="%m/%d/%Y", tz=Sys.timezone())
activity$dt <- format(activity$activitydate, format = "%m/%d/%y")
# sleep
sleep$sleepday=as.POSIXct(sleep$sleepday, format="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone())
sleep$dt <- format(sleep$sleepday, format = "%m/%d/%y")

# Describe the datasets for getting an overview (seperate results of the single values)
# Variable = totalsteps from activity-dataset
mean(activity$totalsteps)
median(activity$totalsteps)
range(activity$totalsteps)
IQR(activity$totalsteps)

# Variable = totalminutesasleep from the sleep-dataset
## also show the average time in hours with "totalhoursasleep"

sleep %>% 
  mutate(totalhoursasleep=totalminutesasleep/60) %>% 
  summarise(mean(totalhoursasleep))

mean(sleep$totalminutesasleep)
median(sleep$totalminutesasleep)
range(sleep$totalminutesasleep)
IQR(sleep$totalminutesasleep)

# Summarise the data
summary(sleep)
summary(activity)

## Merging the datasets now
activity_sleep_merged <- merge(activity, sleep, by=c("id", "dt"))
View(activity_sleep_merged[1:20,1:20])
str(activity)

# creating a subset of the dataset for analyzing the variables I am interested in
df_as <- subset(activity_sleep_merged, select=c("id","dt","totalsteps","totaldistance",
         "veryactivedistance", "calories", "totalminutesasleep"))
nrow(df_as) # only 410 rows left

### Save final data set
setwd(path3)
getwd()
save(df_as,file="activity_sleep.Rda")


####### ####### ####### ####### ####### #######
####### ####### Analyze phase ####### #########
####### ####### ####### ####### ####### #######

###Load data
load("activity_sleep.Rda")

## generate the mean values for every user for some variables in the dataset "average_dist"
average_dist <- df_as %>%
  group_by(id) %>%
  summarise (mean_steps = mean(totalsteps), mean_calories = mean(calories), mean_sleep = mean(totalminutesasleep),
             mean_activedist = mean(veryactivedistance), mean_dist = mean(totaldistance))
head(average_dist)

## generate active groups in relation to the steps they made 
average_dist$steps_group[which(average_dist$mean_steps <5000)] <- 1
average_dist$steps_group[which(average_dist$mean_steps >=5000 & average_dist$mean_steps<7500)] <- 2
average_dist$steps_group[which(average_dist$mean_steps >=7500 & average_dist$mean_steps<10000)] <- 3
average_dist$steps_group[which(average_dist$mean_steps >=10000)] <- 4
## label values
average_dist$steps_group <- ordered(average_dist$steps_group, levels=c(1,2,3,4),
                               labels=c("G1: <5000", "G2: >=5000 & <7500", 
                                        "G3: >=7500 & <1000", "G4: >=10000"))
## Showing the number of groups
average_dist %>% 
  group_by(steps_group) %>% 
  summarise(n = n())

## Now I will create a new data frame with the percentage of each user to show frequencies 
## of the number of groups in a box plot, bargraph and so forth

ggplot(data=average_dist, aes(x=steps_group)) +
  geom_bar(fill="steelblue") +
  labs(y="Frequency", x="Groups from 1-4") +
  ggtitle("Frequency of the different groups") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_text(aes(label=stat(count)), stat="count", vjust=-1)


## scatterplot sleep und steps

ggscatter(average_dist, x = "mean_steps", y = "mean_calories", add ="reg.line") +
    geom_point(color="green") +
    geom_smooth(formula = y ~ x, method = "lm") +
    stat_regline_equation(label.y = 3600, label.x = 1500) +
    stat_cor(aes(label = paste(..rr.label..)), label.y = 3500, label.x = 1500) +
    labs(x="Average steps", y="Average calories", 
         title="Scatterplot with the average number of steps and calories") +
    theme(plot.title = element_text(hjust = 0.5, size=12)) 
  
## The b-coefficient of 0.058 of the regression equation indicates that for 1000 
## additional steps, on average 50.8 calories more are consumed
## R² means, that the x-value "Average steps" explains 12% of the variance 
## of the y value "Average calories"


## Is there a relationship between sleep minutes and steps respectivley very active phases? 
ggarrange(
  ggplot(df_as, aes(x=veryactivedistance, y=totalminutesasleep)) +
    geom_jitter() +
    geom_smooth(color = "blue") + 
    labs(title = "Very active phase and Sleeptime (Minutes)", x = "Very active (Distance in km)", 
         y= "Minutes asleep") +
    theme(panel.background = element_blank(),
          plot.title = element_text( size=12)), 
  ggplot(df_as, aes(x=veryactivedistance, y=calories))+
    geom_jitter() +
    geom_smooth(color = "red") + 
    labs(title = "Very active phase and calories", x = "Very active (Distance in km)", 
         y= "calories") +
    theme(panel.background = element_blank(),
          plot.title = element_text( size=12))
)

## Linegraph for every person at every time 
## First index values to get the number of rows for each individual

# First creating a subset with the variables that are needed for the visualization
df_line <- subset(df_as, select=c('id', 'totalsteps', 'calories', 'totalminutesasleep'))

# How many days there are for each person?
df_line$help <- 1
df_line$days <- ave(df_line$help, by=df_line$id, FUN=cumsum)  #days numbered consecutively (within person)
nrow(df_line[df_line$days==1,]) #number of persons


#  progression of total steps taken over time

df_line %>% 
  ggplot(aes(x=days, y=totalsteps)) + 
  geom_point(size = 2, colour = "darkgreen", alpha = 0.5) + 
  geom_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1) +
  labs(x="Days of recording", y="Steps taken", 
       title = "Days of recording and total number of steps") +
  theme(plot.title = element_text(hjust = 0.5, size=12)) +
  theme_bw()

#  Change in calories consumed over time
df_line %>% 
  ggplot(aes(x=days, y=calories)) + 
  geom_point(size = 2, colour = "darkred", alpha = 0.5) + 
  geom_smooth() +
  labs(x="Days of recording", y="calories", 
       title = "Change in calories consumed over time") +
  theme(plot.title = element_text(hjust = 0.5, size=12)) +
  theme_bw()





