## Case Study (google analytics)
## Sören Nonnengart
## 05-25-2022

###### ###### ###### ###### ###### ###### 
######### Ask Phase ####### ###### ###### 
###### ###### ###### ###### ###### ###### 

# About the company
Bellabeat is a high-tech company that manufactures health-focused smart products. One of the
founders, Urška Sršen, used her background as an artist to develop beautifully designed technology 
that informs and inspires women around the world. Collecting data on

- activity, 
- sleep, 
- stress and
- reproductive health 

has allowed Bellabeat to empower women with knowledge about their own health and habits. 
Since it was founded in 2013, Bellabeat has grown rapidly and quickly positioned itself as a 
tech-driven wellness company for women

# Questions for the analysis
1. What are some trends in smart device usage?
  
  A: According to Statista, the current number of smartphone users worldwide today is 6.648 billion. 
This means that 83.72 % of the world’s population owns a smartphone.The trend thus shows that in 
the near future almost all people worldwide could own a smartphone. It is estimated that 7.33 billion 
people could already own a smartphone by 2025.
(Source: https://www.bankmycell.com/blog/how-many-phones-are-in-the-world#:~:text=According%20to%20Statista%2C%20the%20current,world's%20population%20owns%20a%20smartphone.)    
  Another interesting study by Seifert & Vandelanotte (2021) shows that 75.0% of older adults used at 
  least one mobile device; 22.9 % of them used health-related apps. Younger individuals and those with 
  a strong interest in new technology had a higher likelihood of using health apps
  (Source: https://www.researchgate.net/publication/354050165_The_Use_of_Wearables_and_Health_Apps_and_the_Willingness_to_Share_Self-Collected_Data_among_Older_Adults#:~:text=Results%2075.0%25%20of%20the%20participants,likelihood%20of%20using%20health%20apps.)
    According to Statista, it can also be shown that these apps are esspecially used for fitness-tracking 
    (Source: https://www.statista.com/forecasts/832132/usage-of-health-apps-and-smart-health-devices-in-the-us)
    
    2. How could these trends apply to Bellabeat customers?
      
      A: Bellabeat customers are perfectly fit into this trend because the probability is really high that more
    and more people will use a smartphone in the future. It is also a fact that health has become a really 
    important part in the people's daily life. Therefore, the probability is high that this trend will 
    continue
    
  3. How could these trends help influence Bellabeat marketing strategy 
  
    A: This trend shows that it could be more worthwhile to target a younger customer base with 
    Bellabeat's products. But there should also be an interest in targeting older people since it can 
    be assumed that demand here will also increase in the future.
    (Source: https://www.researchgate.net/publication/354050165_The_Use_of_Wearables_and_Health_Apps_and_the_Willingness_to_Share_Self-Collected_Data_among_Older_Adults#:~:text=Results%2075.0%25%20of%20the%20participants,likelihood%20of%20using%20health%20apps.)
      
      # Business task
      Identify potential opportunities for growth and recommendations for the Bellabeat marketing strategy 
      improvement based on trends in smart device usage.
      
      
      ###################################################################################################
      ###################################################################################################
      
      ###### ###### ###### ###### ###### ###### 
      ####### ###### Prepare Phase ##### ######
      ###### ###### ###### ###### ###### ###### 
      
      Which dataset will be used for the analysis?
        - The data source used for this case study is called "FitBit Fitness Tracker Data". 
      - This dataset is stored in Kaggle and was made available through Mobius.
      - As it is suggested by google analytics and is free to download in Kaggle it is guaranteed
      that the data is open-source and can be used without hesitation for statistical analyses.
      - These datasets were generated by respondents to a distributed survey via Amazon Mechanical Turk 
      between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker 
      data, including minute-level output for physical activity, heart rate, and sleep monitoring. 
      Variation between output represents use of different types of Fitbit trackers and individual 
      tracking behaviors/preferences.
      
      
      rm(list=ls()) #delete all objects in working memory
      
      ## packages 
      library(foreign)
      library(tidyverse)
      library(lubridate)
      library(dplyr)
      library(ggplot2)
      library(tidyr)
      library(here)
      library(janitor)
      library(plm)
      
      
      ## data.frame
      # Directories
      path1 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/results"   
      path2 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/data_orig" #directory of original data
      path3 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/data_prep" #directory of prepared datasets
      path4 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/tables" 
      path5 <- "/Users/sorennonnengart/Desktop/google analytics/Case study/Bellabeat/graphs" 
      
      getwd()
      setwd(path2)
      getwd()
      
      # read csv_data for analysis
      activity <- read.csv("dailyActivity_merged.csv", na="NA", sep=",")
      sleep <- read.csv("sleepDay_merged.csv", na="NA", sep=",")
      
      
      # Now I will preview all the selected data frames for checking the summary of each column.
      # Show first 10 observations for first 5 variables 
      View(activity[1:10,1:5])
      str(activity)
      
      View(sleep[1:10,1:5])
      str(sleep)